### ISSUE TITLE
TypeScript typings cannot be found

### ISSUE THREAD

**Issue by OTTOxMarc** [SAP/odata-library#102]
Hello, I am wondering if there is something wrong with the TypeScript typings.

I feel like I have the most minimal setup and still cannot get odata-library to work with typescript.

My nodejs version is `v18.14.0`.

Basically I did

```bash
npm init
npm install typescript ts-node -D
npm install @sap_oss/odata-library
tsc --init
```

which results in the following files
### package.json
```json
{
  "name": "odata-client",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "ts-node index.ts",
  },
  "dependencies": {
    "@sap_oss/odata-library": "^2.1.1"
  },
  "devDependencies": {
    "ts-node": "^10.9.1",
    "typescript": "^4.9.5"
  }
}
```

#### tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

But when using it in my `.ts` file it shows an error `ts(7016) - Could not find a declaration file for module` 

```ts
import {  } from "@sap_oss/odata-library";
```

Usually typed packages have a small icon on npmjs.com where you can directly see if they include types or provide them via `DefinitelyTyped`.

![image](https://user-images.githubusercontent.com/65161626/218711850-da8aceb3-b19e-405e-b7d9-ac3c85c44e7a.png)

![image](https://user-images.githubusercontent.com/65161626/218712165-78db1ace-d54d-487b-b0c8-a7b61f9d3eee.png)

But this doesn't seem to be the case with this package :/

![image](https://user-images.githubusercontent.com/65161626/218712918-24f986a7-3ea2-40de-891a-2969e0e14f89.png)

Maybe @szalayak can help since he created the PR? Am I missing some configuration?

**Comment by szalayak** [comment]
There was an error in the package.json file and the @types folder wasn't set as the type location - I've fixed this in a subsequent PR (https://github.com/SAP/odata-library/pull/101), but it doesn't seem to have made it into a release yet 

However the library needs further work to function with typescript, as some of the JSDoc that typescript uses to generate the types contains typos/errors so needs fixing. I'll attempt to do it if I get some time, but anyone else is welcome to contribute of course
