### ISSUE TITLE
Faulty calculation path generated for GET with $filter

### ISSUE THREAD

**Issue by nair-sumesh** [SAP/odata-library#122]
Hi,

### Problem Statement
We have a API automation test script using the `odata-library` to test our RAP-V4 app.
Recently we upgraded the `odata-library` version from 2.2.4 to **2.3.1**.
Since this upgrade we have observed that the URL path calculated for a **GET** request with **$filter** is inserting the `key` params from the previous API call.

The API execution call flow:
1. Create the object via API.
2. Call bound action Prepare via API. Has `key` parameters.
3. Call bound action Activate via API. Has `key` parameters.
5. Read (GET) list for the same entity set with $filters. This has no `key` parameters and is failing after the upgrade as the URL generated is with the `key` additions. 

#### URL Generated 
*@sap_oss/odata-library*: `2.2.4`
```url
https://<server>/...../0001/RootEntity?$filter=RootEntityID%20eq%27RootEntity_SANITY_1706099821%27&$format=json&$skip=0&$top=1
 ```

*@sap_oss/odata-library*: `2.3.1`
```url
https://<server>/...../0001/RootEntity?(JRootEntityUUID=9b5ecdc1-c70e-1ede-aeec-9f801f9efd50,IsActiveEntity=false)?$filter=RootEntityID%20eq%27RootEntity_SANITY_1706099821%27&$format=json&$skip=0&$top=1
 ```

### Analysis
What we also found is that the method [calculatePath()](https://github.com/SAP/odata-library/blob/master/lib/engine/RequestDefinition.js#L484-L492) is returning the incorrect URL path.
As per observation, the `foundResponseType` variable is returning a value **3** which does not exists in the `requestPathCalculate` array.
**Expectation** is to retrieve the path using value **2**.
<img width="1728" alt="image" src="https://github.com/SAP/odata-library/assets/12034160/698c4cb3-5def-45ef-b3f4-a9a4f35525e4">

Regards,
SN

**Comment by jakub-vaclavik-sap** [comment]
Already fixed in PR 121. Calculation is correct for set values, added automatic reset for entity, when bound action on an instance is called.
