### ISSUE TITLE
How to call the static action using odata-library

### ISSUE THREAD

**Issue by ShuqiLv** [SAP/odata-library#127]
Hi Experts,
I'm using the odata-library to test my api, but I'm facing some problems when I call the odata action.
Below is my code, maybe the parameter is incorrect.
I got the error: service2.Post is undefined.
'Post' is action name.
```
      const settings = {
        url: variables.srvsUrlApiPostAcq,
        auth: {
          headers: {
            Username: username,
            Password: password
          }
        }
      };
      const service2 = new Service(settings);
      return await service2.Post(payload);
```
Please check the metadata https://hbr-715-api.devsys.net.sap/sap/opu/odata4/sap/api_fixedassetacquisition/srvd_a2x/sap/fixedassetacquisition/0001//$metadata

![image](https://github.com/SAP/odata-library/assets/45410472/5a2cfd3b-e7aa-41ca-accd-38bb6afa2931)

**Comment by ShuqiLv** [comment]
And I've also tried the bound action solution, still doesn't.
It says: 'this.srv.FixedAssetAcquisition.key(...).Post is not a function'

**Comment by jakub-vaclavik-sap** [comment]
The 'static' is in RAP service implementation, there are only Bound and Unbound actions in OData. It would seem appropriate to expose static 'actions' as Unbound Actions but RAP implementation expose them as Bound Actions, but bound to collection type. Probably to allow usage of overloads. How to call it is described in [docu](https://github.com/SAP/odata-library/blob/master/doc/ACTIONS.md), just skip the `key(...)` part.
