### ISSUE TITLE
PATCH request support for ODATA

### ISSUE THREAD

**Issue by dineshbhandarkar** [SAP/odata-library#19]
Hello Colleagues,

We are using Vyper for ODATA automation. For automating the script, in some payloads we use PATCH request. Could it be possible to support PATCH request.

Regards,
Dinesh

**Comment by norbertvolf** [comment]
Hi Dinesh,

I have created PATCH implementation in the attached pull request.  I will be happy if you find some time to check it.

Norbert

**Comment by norbertvolf** [comment]
Hi Dinesh,

I have published version with PATCH support

https://www.npmjs.com/package/@sap_oss/odata-library/v/0.9.12

**Comment by dineshbhandarkar** [comment]
Thanks a lot for your help.
