### ISSUE TITLE
Rejects batch when any request fails

### ISSUE THREAD

**Issue by zverbikadam** [SAP/odata-library#26]
Sending wrong value to database through Batch returns:
`Error: 400 - Invalid response inside Batch.` 
instead of
 `Bad Request` message.

**Comment by norbertvolf** [comment]
Hi Adam,

odata-library rejects the batch request when any of request inside batch returns error. It is different behavior than natural behavior in browser. Browser receives batch as with status code 202 which is correct and later some odata library in browser (ODataModel from SAPUI5 for example) rejects error. 

I have decided to change the behavior inside odata-library to follow the browser behavior. The "sendBatch" method will be rejected only when all batches are rejected. In other cases returns all results or errors. Pls wait for new version.

**Comment by norbertvolf** [comment]
Hi Adam,

I have published the new version 0.9.13. You can see particular error as result of batch instead of reject whole batch request after error of one request in issue.
