### ISSUE TITLE
Cannot get constructor URL while creating new Service Instance (Client side requests)

### ISSUE THREAD

**Issue by stephan-pichler** [SAP/odata-library#29]
Whilte creating service instance via `let service = new Service({...})`, the following typeError in /@sap_oss/odata-library/lib/agent/url.js:90 appears:

**TypeError: URL is not a constructor**

![image](https://user-images.githubusercontent.com/69247572/114549315-23201d00-9c61-11eb-92c8-3a883357a4cd.png)

Already tried different auth params as mentioned in the docs.

**Comment by norbertvolf** [comment]
Hi Stephan,

It looks like old version Node. Which version do you use?

URL constructor is supported by 10.0.0 ...

**Comment by stephan-pichler** [comment]
Hi Norbert, i'm using node v15.1.0 .

**Comment by norbertvolf** [comment]
Hi Stephan, 

I have tried current version 15.14.0 with password inside URL and also in password definition in auth property of settings and It works for me.

Is it possible to give me more information?

**Comment by phipsalabim** [comment]
Hi,

Just wanted to confirm the issue.

node version: 12.18.4

auth or no auth makes no difference. the demo below tries to connect to the northwind service

[demo sandbox here](https://codesandbox.io/s/cocky-hypatia-uphdy)

**Comment by norbertvolf** [comment]
> Hi,
> Just wanted to confirm the issue.
> node version: 12.18.4
> auth or no auth makes no difference. the demo below tries to connect to the northwind service
> [demo sandbox here](https://codesandbox.io/s/cocky-hypatia-uphdy)

Hi,

Thank you for confirmation. The odata-library is not working in browser. I have understood from the sandbox You have tried to use brwoser environment to use odata-library. 

I want to keep issue still open, because I would like to support browser environment by odata-library.
