### ISSUE TITLE
How to use this odata-library to authenticate users by SAML2.0?

### ISSUE THREAD

**Issue by JunyanHe** [SAP/odata-library#51]
My S/4 Hana version is 1809. The system is protected by SAML2.0 . How to use this odata-library to authenticate users?

**Comment by norbertvolf** [comment]
Hi JunyanHe,

The authentication over SAML is depends on the login form :(

I have tried implement authentication over SAMl, but it does not work with all IdP login form. To solve your issue I have to see your IdP login form.  Is the form public?

**Comment by JunyanHe** [comment]
Hi norbertvolf,
Thank you! But my IDP and SP are in local network that can not be accessed from internet.
