### ISSUE TITLE
Deep Create support for OData V4

### ISSUE THREAD

**Issue by pavanr1456** [SAP/odata-library#68]
Hello,

When I try to use POST with Deep Insert I encounter the below error.

entityTypeModelStart.navigationPropertyAssociationTo is not a function
    at EntitySet.processNavigationPropertyItems (C:\Users\<>\AppData\Roaming\npm\node_modules\qmate\node_modules\@sap_oss\odata-library\lib\engine\QueryableResource.js:547:48)

Could you confirm if this is a supported feature currently?

**Comment by pavanr1456** [comment]
It goes something like this:

`const Service = require("@sap_oss/odata-library").Service;
const PAYLOAD = {
  "PurchaseRequisitionType": "NB",
  "PurReqnDescription": "Created from Qmate E2E",
  "SourceDetermination": false,
  "PurReqnDoOnlyValidation": false,
  "_PurchaseRequisitionItem": [
    {
      "PurchaseRequisitionItemText": "Created from Qmate E2E",
      "PurchasingOrganization": "1010",
      "PurchasingGroup": "002",
      "Plant": "1010",
      "MaterialGroup": "L002",
      "AccountAssignmentCategory": "U",
      "RequestedQuantity": 10,
      "BaseUnit": "EA",
      "BaseUnitISOCode": "EA",
      "PurchaseRequisitionPrice": 10.0,
      "PurReqnPriceQuantity": 1,
      "PurReqnItemCurrency": "EUR"
    }
  ]
}


process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;

let url = "https://<system-client>-api.wdf.sap.corp/sap/opu/odata4/sap/api_purchaserequisition_2/srvd_a2x/sap/purchaserequisition/0001/";
let user = <User ID>;
let password = <PWD>;
let service = new Service({
  url: url,
  auth: {
    username: user,
    password: password
  },
  parameters: {
    documentation: ["heading", "quickinfo"],
    language: "EN"
  },
  strict: false,
  logger: console
});

service.init
  .then(() => {
    return service.PurchaseReqn.post(PAYLOAD);
  })
  .then(results => {
    console.log("Purchase Req", results);
  });`

**Comment by norbertvolf** [comment]
Hi,

I have released the deep insert for odatav4 in 1.0.4 version
