### ISSUE TITLE
Service initialization with communication user fails

### ISSUE THREAD

**Issue by heraldantony** [SAP/odata-library#76]
A user created with "Maintain Communication User" can access an odata service with basic authentication but cannot login through SAML.
This odata service tries SAML, and then basic authentication.

For a communication user SAML login fails. The login page is returned with the error message and this service  keeps retrying SAML login indefinitely.

To make this service work with communication users, the code should switch to and try basic authentication, if login credentials don't work for SAML, i.e. after a few retries with SAML login.

**Comment by norbertvolf** [comment]
Hi,

We use the procedure (SAML , Basic Auth, None Auth), becuase it is enough for our cases, but it is little bit magic ....

My proposal how to solve the bug is add parameter which force auth basic for authentication.

ex.:
```
const service = new Service({
  url: "https://localhost/service/",
  annotationsUrl: "https://localhost/serviceMetadata/annotations",
  auth: {
   type: "basic",
    username: "foo",
    password: "bar",
  },
  parameters: {
    //Define initial request by $metadata?sap-client=902&sap-documentation=&sap-language=EN
    "sap-client": "902",
    "sap-documentation": ["heading", "quickinfo"],
    "sap-language": "EN",
  },
  strict: false, // ignore non critical errors, e.g. orphaned annotations
});
```

Is it ok for you?

**Comment by heraldantony** [comment]
Sorry for the delay in my reply. That should work.

Although you would still need to fix SAML login so that it stops after a few retries, instead of endlessly retrying for a communication user.

**Comment by heraldantony** [comment]
Please fix this according to your proposal, by forcing basic authentication when `type: "basic"` is passed in the parameters.

**Comment by norbertvolf** [comment]
Hi,

I have released [odata-library](https://www.npmjs.com/package/@sap_oss/odata-library) 1.0.5 which contains [auth type in object initialization
](https://github.com/SAP/odata-library/blob/master/doc/INITIALIZE.md#initialize-by-object).
