### ISSUE TITLE
Support OAuth / Custom Headers

### ISSUE THREAD

**Issue by OTTOxMarc** [SAP/odata-library#82]
I have an OData service that is made available via SAP CPI and uses OAuth (Bearer token). Not sure how to access this API because it seems like you cannot pass custom headers to the Service constructors. Enabling OAuth would just require passing the header param `Authorization` with a value of `Bearer <your_token>`.

**Comment by norbertvolf** [comment]
I have release new version 1.0.8 which implements headers authentication. You can pass the headers for authorization via environment variable or you can pass the headers to the constructor. The example is in [documentation](https://github.com/SAP/odata-library/blob/master/doc/INITIALIZE.md#headers-authentication).
