### ISSUE TITLE
Please export types

### ISSUE THREAD

**Issue by szalayak** [SAP/odata-library#89]
It'd be very useful if the library was set up to export types as described here https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html 

I'd like to use this in a typescript project, but at the moment I'm having some difficulty due to the lack of types

**Comment by norbertvolf** [comment]
Hi,

I do not use typescript at all. I have checked the tsc to create the d.ts file from JSDoc, but I have not experienced to test it :( for testing.

If I will just generate the d.ts files for some API to separated branch are you able to test it from some branch?

**Comment by szalayak** [comment]
Hi

Thanks for responding so quickly - I'm happy to send you a PR and contribute with this if that's ok with you as well - or test it if you prefer. This shouldn't change the logic of the package at all, only generate some additional descriptor files.

Let me know what you'd prefer.

Thanks
Akos

**Comment by norbertvolf** [comment]
Hi Akos,

If you will create PR it will be nice. I think it is simpler then create types by me, because I have not experience with it. 

Thanks

Norbert

**Comment by szalayak** [comment]
Hi Norbert

I will do it next week, I should have a little bit of free time :-)

Thanks
Akos

**Comment by szalayak** [comment]
apologies, I've been sick so I haven't been able to do it yet - I'm hoping to send a PR soon

**Comment by szalayak** [comment]
I've created this PR https://github.com/SAP/odata-library/pull/91

**Comment by szalayak** [comment]
apologies, I had the wrong email address on the previous merge, here's my correct PR https://github.com/SAP/odata-library/pull/92

**Comment by norbertvolf** [comment]
Hi all,

I have released new version of odata-library [2.1.0](https://www.npmjs.com/package/@sap_oss/odata-library/v/2.1.0) which contains support for typescript from Akos.

Thanks a lot to Akos
