### ISSUE TITLE
Missing InBound actions

### ISSUE THREAD

**Issue by norbertvolf** [SAP/odata-library#96]
We have odatav4 service.The metadata has an action PostGoodsReceipt, but when i try to get action 

const entity = service.EntitySetName;
console.log(entity.key(keys).PostGoodsReceipt);

is undefined

**Comment by nair-sumesh** [comment]
Hi,

The issue still exists. I am not able to call the standard EDIT action of V4 RAP. The documentation also says:
'We have implemented bound Actions now without aditional parameter.'.

BTW, I saw a merged PR on this topic.

**Comment by jakub-vaclavik-sap** [comment]
Actions parameters are now supported since version 2.3.0. There should be no more issue with calling actions.
